package:
  name: crisp
  version: "2.2.1"

source:
    git_url: https://github.com/hovren/crisp.git
    git_rev: v2.2.1
    
# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - crisp = crisp:main
    #
    # Would create an entry point called crisp that calls crisp.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - mock
    - nose
    - scipy
    - matplotlib

  run:
    - python
    - numpy
    - scipy
    - opencv
    - matplotlib

test:
  # Python imports
  imports:
    - crisp

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/hovren/crisp
  license: GNU General Public License (GPL)
  summary: 'Camera-to-IMU calibration and synchronization toolkit'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
